"""INT8 export and on-desktop verification -- section 9, steps 1 and 2.

The representative dataset must come from the TRAINING split. Drawing it from test
data leaks test statistics into the quantisation parameters and invalidates the
result -- a subtle enough mistake that it is worth the explicit guard below.

Step 2 of the plan matters as much as step 1: verify the quantised model in the Python
interpreter against FP32 on the full test set BEFORE flashing. If accuracy drops more
than about two points, the problem is quantisation, and it is dramatically easier to
debug on a desktop than on a microcontroller.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from . import config as C
from .metrics import classification_metrics, macro_f1_3class


def representative_dataset(X_train: np.ndarray, n: int = C.REPRESENTATIVE_SAMPLES,
                           seed: int = C.SEED):
    """Yield ~n calibration windows drawn from TRAINING data only."""
    rng = np.random.default_rng(seed)
    idx = rng.choice(len(X_train), size=min(n, len(X_train)), replace=False)

    def gen():
        for i in idx:
            yield [X_train[i : i + 1].astype(np.float32)]

    return gen


def to_int8_tflite(model, X_train: np.ndarray, out_path: str | Path,
                   n_rep: int = C.REPRESENTATIVE_SAMPLES) -> bytes:
    """Full integer quantisation, int8 in and out."""
    import tensorflow as tf

    conv = tf.lite.TFLiteConverter.from_keras_model(model)
    conv.optimizations = [tf.lite.Optimize.DEFAULT]
    conv.representative_dataset = representative_dataset(X_train, n_rep)
    conv.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    conv.inference_input_type = tf.int8
    conv.inference_output_type = tf.int8
    blob = conv.convert()
    Path(out_path).write_bytes(blob)
    return blob


def tflite_predict(model_path: str | Path, X: np.ndarray, batch_log: int = 0) -> np.ndarray:
    """Run the quantised model through the Python interpreter, one window at a time.

    Quantise the input with the model's own scale and zero point, and dequantise the
    output the same way -- exactly what the firmware does, so a discrepancy here is a
    discrepancy there.
    """
    import tensorflow as tf

    interp = tf.lite.Interpreter(model_path=str(model_path))
    interp.allocate_tensors()
    inp = interp.get_input_details()[0]
    out = interp.get_output_details()[0]
    in_scale, in_zp = inp["quantization"]
    out_scale, out_zp = out["quantization"]

    probs = np.empty((len(X), out["shape"][-1]), dtype=np.float32)
    for i, x in enumerate(X):
        q = np.round(x / in_scale + in_zp).clip(-128, 127).astype(np.int8)
        interp.set_tensor(inp["index"], q[None, ...])
        interp.invoke()
        probs[i] = (interp.get_tensor(out["index"])[0].astype(np.float32) - out_zp) * out_scale
        if batch_log and i % batch_log == 0:
            print(f"    tflite {i}/{len(X)}", flush=True)
    return probs


def quantisation_report(model, model_path: str | Path, X_test: np.ndarray,
                        y_test: np.ndarray) -> dict:
    """Compare FP32 and INT8 on the SAME held-out set -- Table IV's accuracy row."""
    fp32 = model.predict(X_test, batch_size=512, verbose=0)
    int8 = tflite_predict(model_path, X_test)

    f_fp, f_i8 = macro_f1_3class(y_test, fp32), macro_f1_3class(y_test, int8)
    m_fp = classification_metrics(y_test, fp32)
    m_i8 = classification_metrics(y_test, int8)
    drop_pp = (f_fp - f_i8) * 100.0

    rep = {
        "model_bytes": int(Path(model_path).stat().st_size),
        "model_kb": round(Path(model_path).stat().st_size / 1024, 2),
        "fp32_macro_f1": round(f_fp, 4),
        "int8_macro_f1": round(f_i8, 4),
        "macro_f1_drop_pp": round(drop_pp, 3),
        "fp32_sensitivity": round(m_fp["sensitivity"], 4),
        "int8_sensitivity": round(m_i8["sensitivity"], 4),
        "fp32_specificity": round(m_fp["specificity"], 4),
        "int8_specificity": round(m_i8["specificity"], 4),
        "agreement": float((fp32.argmax(1) == int8.argmax(1)).mean()),
        "within_budget_kb": bool(Path(model_path).stat().st_size / 1024 <= C.MAX_MODEL_KB),
        "within_budget_accuracy": bool(drop_pp <= C.MAX_QUANT_ACCURACY_DROP_PP),
    }
    return rep


def to_c_array(tflite_path: str | Path, out_path: str | Path,
               var_name: str = "g_model") -> str:
    """Emit `model.h`. The array is `const` so it lands in flash, not RAM.

    On an ESP32 with 320 KB of usable RAM, a non-const 25 KB array is a meaningful
    fraction of the budget spent for nothing.
    """
    blob = Path(tflite_path).read_bytes()
    lines = [
        "// Generated by fdlib.tflite_export -- do not edit by hand.",
        f"// source: {Path(tflite_path).name}  ({len(blob)} bytes)",
        f"// preprocess signature: {C.preprocess_signature()}",
        "#pragma once",
        "#include <cstdint>",
        "",
        f"alignas(16) const unsigned char {var_name}[] = {{",
    ]
    for i in range(0, len(blob), 12):
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in blob[i : i + 12]) + ",")
    lines += ["};", f"const unsigned int {var_name}_len = {len(blob)};", ""]
    text = "\n".join(lines)
    Path(out_path).write_text(text)
    return text


def estimate_arena_bytes(model_path: str | Path) -> int:
    """Rough tensor-arena estimate, read from the converted model's own tensors.

    Derived from the .tflite rather than the Keras graph: `layer.output_shape` does
    not exist in Keras 3 and silently yielded zero, which put "~0.0 KB" in Table IV.

    The authoritative number is still TFLite Micro's high-water mark on the device.
    This exists only so an architecture that cannot possibly fit is caught before it
    is flashed rather than after.
    """
    import tensorflow as tf

    interp = tf.lite.Interpreter(model_path=str(model_path))
    interp.allocate_tensors()
    sizes = []
    for d in interp.get_tensor_details():
        shape = d.get("shape")
        if shape is None or not len(shape):
            continue
        n = int(np.prod([int(s) for s in shape if int(s) > 0]))
        itemsize = np.dtype(d["dtype"]).itemsize
        sizes.append(n * itemsize)
    sizes.sort(reverse=True)
    # two largest live buffers plus a working margin
    return int(sum(sizes[:2]) * 1.5) if sizes else 0
