// Generated by fdlib.preprocess -- do not edit by hand.
// preprocess signature: 2574e6104c95
// fitted on 200596 training windows from: 200596 windows from 71/89 subjects (seed 1337)
#pragma once
static const float kNormMean[6] = { 0.00258729f, -0.69131702f, -0.02014211f, -0.28653809f, 2.78818130f, 0.09101488f };
static const float kNormStd[6]  = { 0.40943426f, 0.56151086f, 0.46308962f, 31.76609802f, 36.64720917f, 22.56091881f };
