// model_config.h — FROZEN preprocessing constants from the training run
// (generated by tools/make_model_h.py; must never diverge from training)
#pragma once
#define IMU_FS_HZ 50.0f
#define NORM_MEAN { -0.008691f, -0.165269f, -0.032196f, -0.002413f, 0.007117f, -0.000290f }
#define NORM_STD  { 0.087276f, 0.124962f, 0.103810f, 0.061120f, 0.068999f, 0.045150f }
#define INPUT_SCALE 0.11342239f
#define INPUT_ZERO_POINT 12
#define INPUT_SAMPLES 100
#define INPUT_CHANNELS 6
#define ALERT_THRESHOLD 0.6f
#define COOLDOWN_SEC 5.0f
// hardware
#define PIN_BUZZER 4
#define PIN_LED 2
#define I2C_SDA 21
#define I2C_SCL 22
#define MPU6050_ADDR 0x68
// accelerometer / gyroscope configuration (plan 8.2)
#define ACCEL_RANGE 16384   // +-16 g -> 16384 ADC LSB per g (MPU6050)
#define GYRO_RANGE 16.4f    // +-2000 dps -> 16.4 LSB per (deg/s)
// MPU6050 raw -> SI conversion
#define RAW_A_TO_G(x) ((x) / 16384.0f)
#define RAW_G_TO_DPS(x) ((x) / 16.4f)
